#!/bin/bash
#
# run.all.sh - run all slurm jobs for job.h-0mod3.prime-all
#
cd /usr/global/src/cisco/verified-prime/v1-data/job.h-0mod3.prime-all
sbatch sbatch.aaaaa.slurm
sbatch sbatch.aaaab.slurm
sbatch sbatch.aaaac.slurm
sbatch sbatch.aaaad.slurm
sbatch sbatch.aaaae.slurm
sbatch sbatch.aaaaf.slurm
sbatch sbatch.aaaag.slurm
sbatch sbatch.aaaah.slurm
sbatch sbatch.aaaai.slurm
sbatch sbatch.aaaaj.slurm
sbatch sbatch.aaaak.slurm
sbatch sbatch.aaaal.slurm
sbatch sbatch.aaaam.slurm
sbatch sbatch.aaaan.slurm
sbatch sbatch.aaaao.slurm
sbatch sbatch.aaaap.slurm
sbatch sbatch.aaaaq.slurm
sbatch sbatch.aaaar.slurm
sbatch sbatch.aaaas.slurm
sbatch sbatch.aaaat.slurm
sbatch sbatch.aaaau.slurm
sbatch sbatch.aaaav.slurm
sbatch sbatch.aaaaw.slurm
sbatch sbatch.aaaax.slurm
sbatch sbatch.aaaay.slurm
sbatch sbatch.aaaaz.slurm
sbatch sbatch.aaaba.slurm
sbatch sbatch.aaabb.slurm
sbatch sbatch.aaabc.slurm
sbatch sbatch.aaabd.slurm
sbatch sbatch.aaabe.slurm
sbatch sbatch.aaabf.slurm
sbatch sbatch.aaabg.slurm
sbatch sbatch.aaabh.slurm
sbatch sbatch.aaabi.slurm
sbatch sbatch.aaabj.slurm
sbatch sbatch.aaabk.slurm
sbatch sbatch.aaabl.slurm
sbatch sbatch.aaabm.slurm
sbatch sbatch.aaabn.slurm
sbatch sbatch.aaabo.slurm
sbatch sbatch.aaabp.slurm
sbatch sbatch.aaabq.slurm
sbatch sbatch.aaabr.slurm
sbatch sbatch.aaabs.slurm
sbatch sbatch.aaabt.slurm
sbatch sbatch.aaabu.slurm
sbatch sbatch.aaabv.slurm
sbatch sbatch.aaabw.slurm
sbatch sbatch.aaabx.slurm
sbatch sbatch.aaaby.slurm
sbatch sbatch.aaabz.slurm
sbatch sbatch.aaaca.slurm
sbatch sbatch.aaacb.slurm
sbatch sbatch.aaacc.slurm
sbatch sbatch.aaacd.slurm
sbatch sbatch.aaace.slurm
sbatch sbatch.aaacf.slurm
sbatch sbatch.aaacg.slurm
sbatch sbatch.aaach.slurm
sbatch sbatch.aaaci.slurm
sbatch sbatch.aaacj.slurm
sbatch sbatch.aaack.slurm
sbatch sbatch.aaacl.slurm
sbatch sbatch.aaacm.slurm
sbatch sbatch.aaacn.slurm
sbatch sbatch.aaaco.slurm
sbatch sbatch.aaacp.slurm
sbatch sbatch.aaacq.slurm
sbatch sbatch.aaacr.slurm
sbatch sbatch.aaacs.slurm
sbatch sbatch.aaact.slurm
sbatch sbatch.aaacu.slurm
sbatch sbatch.aaacv.slurm
sbatch sbatch.aaacw.slurm
sbatch sbatch.aaacx.slurm
sbatch sbatch.aaacy.slurm
sbatch sbatch.aaacz.slurm
sbatch sbatch.aaada.slurm
sbatch sbatch.aaadb.slurm
sbatch sbatch.aaadc.slurm
sbatch sbatch.aaadd.slurm
sbatch sbatch.aaade.slurm
sbatch sbatch.aaadf.slurm
sbatch sbatch.aaadg.slurm
